### ISSUE TITLE
如何将模型修改成中文翻译英文

### ISSUE THREAD

**Issue by PipeDream941** [taoztw/Transformer#1]
想问一下，现在这个模型是吧英文翻译成中文。如果我想中文翻译成英文应该如何修改呢。我自己把data的batch中英文对调了。但是结果很差。顺便感谢作者，注释写的很详细，很方便理解。

**Comment by taoztw** [comment]
需要更改data_pre.py文件中`batches.append(Batch(batch_en, batch_cn))`代码,确认一下是否修改正确。其次，翻译效果很差有很多方面的原因，语料的大小质量，分词方式，模型性能等等，这个项目仅仅是一个基线用于理解机器翻译的整个流程，如果想要获得好的结果可以使用fairseq等工具来进行实验。机器翻译WMT等比赛论文可以参考我的博客https://tzer.top/
