### ISSUE TITLE
data

### ISSUE THREAD

**Issue by FreeRotate** [taoztw/Transformer#3]

**Comment by taoztw** [comment]
机器翻译的开源平行语料在这个网站上可以下载。https://opus.nlpl.eu/index.php

**Comment by AhGiao** [comment]
> 

好的 谢谢

**Comment by AhGiao** [comment]
那这个你上传的项目中的data 数据集是从刚刚发的网址中哪个语料库名字提取的能否告知一下，我想基于你这项目中的dataset继续提取一些数据进训练集

**Comment by taoztw** [comment]
具体的数据集我已经忘记了，相对质量较好的语料是https://conferences.unite.un.org/UNCORPUS/zh，其他的数据需要一定的过滤代码
